
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -278;
const int acc_off_y = 58;
const int acc_off_z = -574;
const float acc_scale_x = 14812.792928;
const float acc_scale_y = 17392.001832;
const float acc_scale_z = 18005.712448;

const int magn_off_x = 33;
const int magn_off_y = 180;
const int magn_off_z = -170;
const float magn_scale_x = 216.637434;
const float magn_scale_y = 266.933757;
const float magn_scale_z = 233.234892;
