
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 49;
const int acc_off_y = 490;
const int acc_off_z = -73;
const float acc_scale_x = 16271.717127;
const float acc_scale_y = 16500.140962;
const float acc_scale_z = 16872.489503;

const int magn_off_x = -56;
const int magn_off_y = -75;
const int magn_off_z = -80;
const float magn_scale_x = 190.381796;
const float magn_scale_y = 247.042119;
const float magn_scale_z = 203.656452;
